; Ikoka Pro Meshtastic Device - EBYTE E73-2G4M08 + EBYTE E22-900M30S
; https://github.com/ndoo/ikoka-pro-meshtastic-device
[env:ikoka_pro]
extends = nrf52840_base
board = promicro-nrf52840
board_level = extra
build_flags = ${nrf52840_base.build_flags}
  -I variants/nrf52840/diy/ikoka_pro
  -D PRIVATE_HW
  -D EBYTE_E22
  -D EBYTE_E22_900M30S
build_src_filter = ${nrf52_base.build_src_filter} +<../variants/nrf52840/diy/ikoka_pro>
lib_deps =
  ${nrf52840_base.lib_deps}
debug_tool = jlink

; Ikoka Pro Meshtastic Device v0.9.0 - GPS TX and RX got swapped in PCB v0.9.0
[env:ikoka_pro_v0_9_0]
extends = env:ikoka_pro
build_flags = ${env:ikoka_pro.build_flags}
  -D IKOKA_PRO_V0_9_0
